name: Build, Linter, Test

on:
  push:
    branches: 
      - master
  pull_request:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install flake8
      run: |
        pip install flake8
    - name: Lint with flake8 author
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 yacut --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 yacut --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: cache pip
      uses: actions/cache@v2
      with: 
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Lint with flake8 tests
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 tests --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 tests --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics
    - name: Run tests
      run: |
        py.test
  coverage:
      runs-on: ubuntu-latest
      needs: [ test ]
      steps:
      - uses: actions/checkout@v2
      - name: Install pytest-cov
        run: |
          pip install pytest-cov -r requirements.txt
      - name: Run tests cov
        run: |
          py.test --cov=src/ tests/
